# SPDX-License-Identifier: MIT
name: Bug Report
description: File a bug report to help us improve paper-dl
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: input
    id: version
    attributes:
      label: paper-dl Version
      description: What version of paper-dl are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.11.5"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "Ubuntu 22.04, macOS 13.0, Windows 11"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "paper-dl fails when downloading from arXiv with error..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `paper-dl https://arxiv.org/pdf/...`
        2. See error message
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "The PDF should download and be renamed to Author_Year_Title.pdf"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Error message: NetworkError..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Copy and paste any relevant log output or error messages
      render: shell
      placeholder: |
        $ paper-dl https://arxiv.org/pdf/2301.00001.pdf
        Error: NetworkError: Request timed out after 30 seconds

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context about the problem
      placeholder: "This happens consistently with PDFs larger than 10MB"